### ISSUE TITLE
Korrektur-Modus für Labore

### ISSUE THREAD

**Issue by florianb** [testbefund/meta#5]
Falls das produktiv gehen soll, sollten wir einen failsafe Korrektur-Modus für die Labore vorsehen:

1. Änderungen am Test-Status sollten evtl erst nach einer Karenzzeit von 20 Minuten für Clients sichtbar gemacht werden.
2. Um Tests in der Karenzzeit zu korrigieren kann man die Tracking-ID der fehlerhaften Tests erneut einscannen und das Testergebnis erneut setzen.

**Comment by Niklas345** [comment]
Hey @florianb ,
Das finde ich eine gute Idee. Ich würde folgende Lösung vorschlagen:

- Wir führen einen Status ein, der definiert, dass das Ergebnis eingegben wurde aber noch nicht öffentlich ist "**REVIEW_PENDING**"
- Bei jedem Zugriff prüft das Lambda den **Zeitstempel mit der aktuellen Zeit** (gerne immer UTC). 

1. ist die Nachfrage **innerhalb der Karenzzeit**, wird das Testergebnis (**enum infected**) aus der **Response gelöscht**
2.  ist die Nachfrage nach der Karenzzeit, dann **updated** das Lambda den **status auf DONE** o.Ä. und das Ergebnis wird ausgegeben.

Maximale transparenz für den Nutzer. Die Möglichkeit der Korrektur für das Labor. Grade vor dem Hintergrund HIV Test ist das sehr hilfreich.

Lass uns im selben Zug auch die Karenzzeit an das Objekt klatschen, gerne opaque für den User. So haben wir konfigurations-Optionen. 

Eine Korrektur auch nach dieser Zeit sollte mMn dennoch Möglich sein.

**Comment by florianb** [comment]
Den Transparenz-Gedanken finde ich prima!

Wenn ich dich richtig verstehe geht das Ganze schon fast in die Richtung einer Finite-State-Machine. Und vielleicht macht es Sinn über eine Lösung nachzudenken, die etwas flexibler ist.

Ich habe auch drüber nachgedacht, wie man das gut realisiert, wenn wir aber den "Status" top-level im Objekt haben, erschweren wir uns in Zukunft möglicherweise komplexere Abläufe und Ergebnisse abzubilden. Auch wenn das bislang noch nicht angesprochen wurde, sollten wir auch eine Auiitier-Möglichkeit vorsehen.

Ich hatte dann die Idee, dass man den Top-Level-Status vielleicht versucht zu eliminieren, und stattdessen, einen impliziten Status-Log mit Einträgen vorzusehen - um die Idee zu illustrieren:

```yaml
coronaTestCase:
  personalId: 58XzRgVQk30ohSESuANwIZ
  writePermissions:
   - RohmLrxs7mfJnj4-3GdrE1
  states:
   - ownerId: xgK9lceRaHIdR6V5Wne_mo
     timestamp: 2007-08-31T16:47+00:00
     state: issued
   - ownerId: RohmLrxs7mfJnj4-3GdrE1
     timestamp: 2007-08-31T16:47+00:00
     state: inbox
   - ownerId: RohmLrxs7mfJnj4-3GdrE1
     timestamp: 2007-08-31T16:47+00:00
     state: testStart
```
